apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  # 2 instances pour la tolérance aux pannes
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zouboss/projetfilrouge_backend:latest  # Ton image Docker Hub
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]  # Identique à docker-compose
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"  # Nom du service PostgreSQL
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "zou123"  # À sécuriser avec un Secret !
        - name: DB_NAME
          value: "odc_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30081  # Tu choisis un port entre 30000 et 32767
  type: NodePort

